# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            zübeyir
tagline:          'baba'
description:      '@zubbay, eksi1arti5, ve Github'da beni bulabilirsiniz'
url:              http://eksi1arti5.com
baseurl:          /

author:
  name:           'Zübeyir Bayraktaroğlu'
  url:            https://twitter.com/zubbay

paginate:         5

# Custom vars
version:          0.1

github:				https://github.com/zubeyir
  repo:           
