# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'zubeyir'
tagline:          'baba'
description:      'beni <a href="https://tr.linkedin.com/in/zubeyirbayraktaroglu/" target="_blank">LinkedIn</a>, <a href="http://twitter.com/zubbay" target="_blank">@zubbay</a>, <a href="http://e1a5.com" target="_blank">eksi1arti5</a> ve <a href="https://github.com/zubeyir" target="_blank">Github</a>&apos;da bulabilirsiniz.'
url:              http://zubeyir.github.io
baseurl:          /

author:
  name:           'Zübeyir Bayraktaroğlu'
  url:            https://twitter.com/zubbay

paginate:         5

# Custom vars
version:          1

github:           https://github.com/zubeyir
  repo:/
